name: Deploy to Lightsail

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install rsync
        run: sudo apt-get update && sudo apt-get install -y rsync

      - name: Upload files to Lightsail
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.LIGHTSAIL_HOST }}
          username: ${{ secrets.LIGHTSAIL_USER }}
          key: ${{ secrets.LIGHTSAIL_SSH_KEY }}
          source: "."
          target: "~/app"

      - name: SSH into Lightsail and deploy
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.LIGHTSAIL_HOST }}
          username: ${{ secrets.LIGHTSAIL_USER }}
          key: ${{ secrets.LIGHTSAIL_SSH_KEY }}
          script: |
            # Install Node.js if not already installed
            curl -fsSL https://deb.nodesource.com/setup_18.x | sudo -E bash -
            sudo apt-get install -y nodejs

            # Set up folders
            mkdir -p ~/app/client ~/app/server ~/app/build

            # Write client .env
            echo "VITE_TOMTOM_API_KEY=${{ secrets.VITE_TOMTOM_API_KEY }}" > ~/app/client/.env
            echo "VITE_SUPABASE_URL=${{ secrets.VITE_SUPABASE_URL }}" >> ~/app/client/.env
            echo "VITE_ANON_KEY=${{ secrets.VITE_ANON_KEY }}" >> ~/app/client/.env

            # Write server .env
            echo "TOMTOM_API_KEY=${{ secrets.TOMTOM_API_KEY }}" > ~/app/server/.env
            echo "SUPABASE_PROJECT_ID=${{ secrets.SUPABASE_PROJECT_ID }}" >> ~/app/server/.env
            echo "SUPABASE_JWT_SECRET=${{ secrets.SUPABASE_JWT_SECRET }}" >> ~/app/server/.env
            echo "SUPABASE_ANON_KEY=${{ secrets.SUPABASE_ANON_KEY }}" >> ~/app/server/.env

            # Decode and write credentials.json
            echo "${{ secrets.CREDENTIALS_JSON }}" | base64 -d > ~/app/server/credentials.json

            # Build frontend
            cd ~/app/client
            npm install
            npm run build

            # Move build to server/public
            rm -rf ~/app/server/public
            mkdir -p ~/app/server/public
            cp -r ~/app/client/dist/* ~/app/server/public/

            # Install backend dependencies
            cd ~/app/server
            npm install

            # Create systemd service file
            SERVICE_FILE="/etc/systemd/system/nodeapp.service"
            sudo bash -c "cat > $SERVICE_FILE" <<EOF
            [Unit]
            Description=Node.js App
            After=network.target

            [Service]
            Environment=NODE_ENV=production
            WorkingDirectory=/home/${{ secrets.LIGHTSAIL_USER }}/app/server
            ExecStart=/usr/bin/node index.js
            Restart=always
            RestartSec=10
            StandardOutput=syslog
            StandardError=syslog
            SyslogIdentifier=nodeapp
            User=${{ secrets.LIGHTSAIL_USER }}
            EnvironmentFile=/home/${{ secrets.LIGHTSAIL_USER }}/app/server/.env

            [Install]
            WantedBy=multi-user.target
            EOF

            # Reload systemd, enable and restart the service
            sudo systemctl daemon-reexec
            sudo systemctl daemon-reload
            sudo systemctl enable nodeapp
            sudo systemctl restart nodeapp
